Local release
talknote-inc/MWPhotoBrowser pull request #1
Opened 2019-01-08 06:07 UTC by kimuyonsoku

SDWebImageを4系に上げる

2019-01-08 08:43 UTC, baikay approved these changes
LGTM！

2019-01-08 10:27 UTC, iwaorz requested changes
@baikay review done

2019-01-08 10:27 UTC, iwaorz commented on MWPhotoBrowser.podspec
> +  s.dependency 'SDWebImage', '~> 4.4.3', '!= 3.7.2'
'!= 3.7.2' これの意味がわからないので、もし意味がないなら上部のコメントごと消してほしいんだけど、外部ライブラリなので元の行自体をコメントアウトして、下に正しい記載を書いてほしい

2019-01-08 23:16 UTC, kimuyonsoku commented on MWPhotoBrowser.podspec
> +  s.dependency 'SDWebImage', '~> 4.4.3', '!= 3.7.2'
@iwaorz 
'~> 4.4.3'にした時点で、'!= 3.7.2'は不要でしたので削除しました。

2019-01-09 03:17 UTC, iwaorz approved these changes
@kimuyonsoku  LGTM!

2019-01-09 03:25 UTC, merged